symlinks:
  # Multipart plugins
  - src: ..\packages\jp.co.hololab.uniwebserver.multipart\Plugins~
    dest: ..\unity\UniWebServer\Assets\UniWebServer.Multipart.Plugins

  # Sample folder
  - src: ..\packages\jp.co.hololab.uniwebserver\Samples~
    dest: ..\unity\UniWebServer\Assets\UniWebServer.Samples
  - src: ..\packages\jp.co.hololab.uniwebserver.multipart\Samples~
    dest: ..\unity\UniWebServer\Assets\UniWebServer.Multipart.Samples
